authorization/urls.py
from django.urls import re_path
import authorization.views as authorization

app_name = 'authorization'

urlpatterns = [
    re_path('login/$', authorization.user_login, name='login'),
    re_path('logout/$', authorization.user_logout, name='logout'),
    re_path('register/$', authorization.user_register, name='register'),
    re_path('edit/$', authorization.user_edit, name='edit'),
]

book/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.index, name='index'),
    path('categories/', mainapp.categories, name='categories'),
    path('Interesting_facts_in_the_world_of_books/', mainapp.Interesting_facts_in_the_world_of_books, name='Interesting_facts_in_the_world_of_books'),
    path('Recently_published_books/', mainapp.Recently_published_books, name='Recently_published_books'),
    path('The_authors/', mainapp.The_authors, name='The_authors'),
    path('Top_interesting_authors/', mainapp.Top_interesting_authors, name='Top_interesting_authors'),
    path('Top_interesting_books/', mainapp.Top_interesting_books, name='Top_interesting_books'),
    path('Bookstore/', mainapp.Bookstore, name='Bookstore'),
    path('delivery/', mainapp.delivery, name='delivery'),
    path('product/', mainapp.product, name='product'),
    path('we/', mainapp.we, name='we'),

    re_path(r'^error/$', mainapp.error, name='error'),
    re_path(r'^fail/$', mainapp.fail, name='fail'),
    re_path(r'^success/$', mainapp.success, name='success'),


    re_path('^categories/book/(\d+)/ajax/$', mainapp.categories_book_ajax),
    re_path('^categories/book-categories/(\d+)/ajax/$', mainapp.bookCategories_ajax),

    path('admin/', admin.site.urls),

    re_path('^auth/', include('authorization.urls', namespace='auth')),
    re_path('^map5/', include('chatapp.urls', namespace='chat')),
    re_path('^robokassa/', include('robokassa.urls', namespace='robokassa')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
# from __future__ import unicode_literals

from django.utils.six import python_2_unicode_compatible
# from django.contrib.auth.models import ParkUser

class BookCategory(models.Model):
    name = models.CharField(verbose_name='Название', max_length=64)
    min_age = models.PositiveSmallIntegerField(verbose_name='Минимальный возраст', default=12)
    description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        return f'{self.name} : {self.min_age}'

    class Meta:
        ordering = ['name']
        verbose_name = 'категория книг'
        verbose_name_plural = 'Категории книг'


class Book(models.Model):
    category = models.ForeignKey(BookCategory, verbose_name='Категория',
                                 on_delete=models.CASCADE)  # связь "Один ко многим"
    title = models.CharField(verbose_name='Название', max_length=64)
    price = models.PositiveSmallIntegerField(verbose_name='Цена', default=0)
    description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        return f'{self.title} ({self.category.name}): {self.price} руб'

    class Meta:
        ordering = ['category', 'title']
        verbose_name = 'книга'
        verbose_name_plural = 'Книги'


class Published_books(models.Model):
    title = models.CharField(verbose_name='Название', max_length=128)
    content = models.TextField(verbose_name='Содержание')
    added = models.DateTimeField(verbose_name='Добавлена', auto_now_add=True)
    active = models.BooleanField(verbose_name='Активна', default=False)

    def __str__(self):
        # return f'{self.added:%Y-%m-%d %H:%M:%S}: {self.title} ({self.author})'
        return f'{self.added:%Y-%m-%d %H:%M}: {self.title} - {self.active}'

    class Meta:
        ordering = ['-added', 'title']
        verbose_name = 'вышедшая книга'
        verbose_name_plural = 'Вышедшие книги'


class Interesting_authors(models.Model):
    title = models.CharField(verbose_name='ФИО', max_length=128)
    content = models.TextField(verbose_name='Биография')
    added = models.DateTimeField(verbose_name='Добавлена', auto_now_add=True)
    active = models.BooleanField(verbose_name='Активна', default=False)

    def __str__(self):
        return f'{self.added:%Y-%m-%d %H:%M}: {self.title}  - {self.active}'

    class Meta:
        ordering = ['-added', 'title']
        verbose_name = 'автор'
        verbose_name_plural = 'Топ_авторы'


class Interesting_books(models.Model):
    title = models.CharField(verbose_name='Название', max_length=128)
    content = models.TextField(verbose_name='содержание')
    added = models.DateTimeField(verbose_name='Добавлена', auto_now_add=True)
    active = models.BooleanField(verbose_name='Активна', default=False)

    def __str__(self):
        return f'{self.added:%Y-%m-%d %H:%M}: {self.title}  - {self.active}'

    class Meta:
        ordering = ['-added', 'title']
        verbose_name = 'Книга'
        verbose_name_plural = 'Топ_Книги'

@python_2_unicode_compatible
class SuccessNotification(models.Model):
    InvId = models.IntegerField('Номер заказа', db_index=True)
    OutSum = models.CharField('Сумма', max_length=15)

    created_at = models.DateTimeField('Дата и время получения уведомления', auto_now_add=True)

    class Meta:
        verbose_name = 'Уведомление об успешном платеже'
        verbose_name_plural = 'Уведомления об успешных платежах (ROBOKASSA)'

    def __str__(self):
        return '#{}: {} ({})'.format(self.InvId, self.OutSum, self.created_at)

mainapp/views.py
from django.shortcuts import render
from django. urls import reverse
from mainapp.models import Book, BookCategory, Published_books, Interesting_authors, Interesting_books
from django.http import JsonResponse
from django.template.loader import render_to_string
from authorization.models import ParkUser

# from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from robokassa.forms import RobokassaForm
# from __future__ import unicode_literals
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.views.decorators.csrf import csrf_exempt
from robokassa.conf import USE_POST
from robokassa.forms import ResultURLForm, SuccessRedirectForm, FailRedirectForm
from robokassa.models import SuccessNotification
from robokassa.signals import result_received, success_page_visited, fail_page_visited

# from robokassa.signals import result_received
# from my_app.models import Order

def index(request):
    peoples = []
    if request.user.is_authenticated:
        peoples = ParkUser.objects.exclude(pk=request.user.pk).order_by('last_name', 'first_name')
    context = {

        'peoples': peoples,
    }
    return render(request, 'mainapp/index.html', context)

def categories(request):
    book_categories = BookCategory.objects.all()
    books = Book.objects.all()

    context = {
        'book_categories': book_categories,
        'books': books,
    }
    return render(request, 'mainapp/categories.html', context)

def Interesting_facts_in_the_world_of_books(reguest):
    return render(reguest, 'mainapp/Interesting_facts_in_the_world_of_books.html')

def Recently_published_books(reguest):
    published_books = Published_books.objects.all()

    context = {
        'published_books': published_books,
    }
    return render(reguest, 'mainapp/Recently_published_books.html', context)

def The_authors(reguest):
    return render(reguest, 'mainapp/The_authors.html')

def Top_interesting_authors(reguest):
    interesting_authors = Interesting_authors.objects.all()

    context = {
        'interesting_authors': interesting_authors,
    }
    return render(reguest, 'mainapp/Top_interesting_authors.html', context)

def Top_interesting_books(reguest):
    interesting_books = Interesting_books.objects.all()

    context = {
        'interesting_books': interesting_books,
    }
    return render(reguest, 'mainapp/Top_interesting_books.html', context)

def categories_book_ajax(request, book_pk):
    if request.is_ajax():
        current_book = Book.objects.filter(pk=book_pk).first()

        context = {
            'book_description': current_book.description

        }
        current_book_description = render_to_string('mainapp/book_desc.html', context)
        print('клик на книге передали контроллеру', book_pk)
        print(f'книга: {current_book.title}')

        context = {
            'current_book': current_book.title,
            'book_description': current_book_description,
        }
        return JsonResponse(context)


def bookCategories_ajax(request, categories_pk):
    if request.is_ajax():
        current_bookCategory = BookCategory.objects.filter(pk=categories_pk).first()

        context = {
            'bookCategory_description': current_bookCategory.description

        }

        current_bookCategory_description = render_to_string('mainapp/book_categories_desc.html', context)
        print(current_bookCategory_description)
        print(f'книга: {current_bookCategory.name}')

        context = {
            'current_bookCategory': current_bookCategory.name,
            'bookCategory_description': current_bookCategory_description,
        }
        return JsonResponse(context)

def Bookstore(request):
    return render(request, 'mainapp/Bookstore.html')


def delivery(request):
    return render(request, 'mainapp/delivery.html')


def product(request):
    return render(request, 'mainapp/product.html')


def we(request):
    return render(request, 'mainapp/we.html')

@login_required
def product(request, order_id):
    return render(request, 'product.html', {'form': form})

    order = get_object_or_404(Order, pk=order_id)

form = RobokassaForm(initial={
    'OutSum': 'order_title',
    'InvId': 'order_id',
    'Desc': 'order_name',
    # 'Email': request.user.email,
    # 'IncCurrLabel': '',
    # 'Culture': 'ru'
})

# def payment_received(sender, **kwargs):
# order = Order.objects.get(id=kwargs['InvId'])
# order.status = 'paid'
# order.paid_sum = kwargs['OutSum']
# order.extra_param = kwargs['extra']['my_param']
# order.save()
#
# result_received.connect(payment_received)

@csrf_exempt
def receive_result(request):
    """Обработчик для ResultURL."""
    data = request.POST if USE_POST else request.GET
    form = ResultURLForm(data)
    if form.is_valid():
        inv_id, out_sum = form.cleaned_data['InvId'], form.cleaned_data['OutSum']

        # сохраняем данные об успешном уведомлении в базе, чтобы
        # можно было выполнить дополнительную проверку на странице успешного
        # заказа
        notification = SuccessNotification.objects.create(InvId=inv_id, OutSum=out_sum)

        return HttpResponse('OK%s' % inv_id)
    return HttpResponse('error: bad signature')


@csrf_exempt
def success(request, template_name='robokassa/success.html', extra_context=None,
            error_template_name='robokassa/error.html'):
    """Обработчик для SuccessURL"""

    data = request.POST if USE_POST else request.GET
    form = SuccessRedirectForm(data)
    if form.is_valid():
        inv_id, out_sum = form.cleaned_data['InvId'], form.cleaned_data['OutSum']

        # в случае, когда не используется строгая проверка, действия с заказом
        # можно осуществлять в обработчике сигнала robokassa.signals.success_page_visited
        success_page_visited.send(sender=form, InvId=inv_id, OutSum=out_sum,
                                  extra=form.extra_params())

        context = {'InvId': inv_id, 'OutSum': out_sum, 'form': form}
        context.update(form.extra_params())
        context.update(extra_context or {})
        return TemplateResponse(request, template_name, context)

    return TemplateResponse(request, error_template_name, {'form': form})


@csrf_exempt
def fail(request, template_name='robokassa/fail.html', extra_context=None,
         error_template_name='robokassa/error.html'):
    """Обработчик для FailURL"""

    data = request.POST if USE_POST else request.GET
    form = FailRedirectForm(data)
    if form.is_valid():
        inv_id, out_sum = form.cleaned_data['InvId'], form.cleaned_data['OutSum']

        # дополнительные действия с заказом (например, смену его статуса для
        # разблокировки товара на складе) можно осуществить в обработчике
        # сигнала robokassa.signals.fail_page_visited
        fail_page_visited.send(sender=form, InvId=inv_id, OutSum=out_sum,
                               extra=form.extra_params())

        context = {'InvId': inv_id, 'OutSum': out_sum, 'form': form}
        context.update(form.extra_params())
        context.update(extra_context or {})
        return TemplateResponse(request, template_name, context)

    return TemplateResponse(request, error_template_name, {'form': form})

def error(request):
    return render(request, 'mainapp/error.html')

mainapp/templates/mainapp/Bookstore.html
{% extends 'mainapp/base.html'%}

{% block title %}
    <title>Книжный магазинчик</title>
{% endblock %}

{% block content %}

<p>Я-Читалочка. Небольшой книжный магазинчик который только только начинает развиваться. Здесь тебя ждёт:
- адекватные цены;
- интересные книги;
- разнообразные жанры и авторы;
- доставка;
Этот магазинчик продолжение книжной социальной сети Читалочка.</p>

{% endblock %}

mainapp/templates/mainapp/Interesting_facts_in_the_world_of_books.html
{% extends 'mainapp/base.html'%}

{% block title %}
    <title>Факты</title>
{% endblock %}

{% block content %}

<h1>Интересные факты в мире книг</h1>


<h4>Топ-6 фактов о книгах</h4>

<ol>
    <li>Всего на Земле 129864880 книг.</li>
    <li>Первое место среди всех книг мирового пространства отдается Библии.</li>
    <li>Ребенок 4-6 лет лучше всего приучается к чтению книги.</li>
    <li>Большое количество читателей теряют интерес к книге на 18 странице.</li>
    <li>Свиток Дхарани – это самая древнейшая печатная книга.</li>
    <li>Одна из самых необычных книг в мире – это «Божественная комедия» Данте, написанная бенедиктинским монахом Габриэлем Челани на листе бумаги размером 80 на 60 см.</li>
</ol>

{% endblock %}

mainapp/templates/mainapp/Recently_published_books.html
{% extends 'mainapp/base.html'%}

{% block title %}
    <title>Вышедшие книги</title>
{% endblock %}

{% block content %}
<div class="published_books">
    <h1>Недавно вышедшие книги</h1>

    <h3>Книги за май-июнь 2020 года</h3>
    <ul>
        {% for published_book in published_books %}
            <li>
                {{published_book.title}} {{published_book.content}}
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mainapp/templates/mainapp/The_authors.html
{% extends 'mainapp/base.html'%}

{% block title %}
    <title>Авторы</title>
{% endblock %}

{% block content %}
   <h1>Авторы</h1>

<h2>  Пушкин А.С. (6.06.1779 - 10.02.1837 гг.)</h2>
    <p> В период ухаживаний за своей будущей супругой Натальей Пушкин много рассказывал своим друзьям о ней и при этом обычно произносил:
<p> «Я восхищен, я очарован,</p>
 <p>   Короче – я огончарован!». </p>

<p> Известно, что Пушкин был очень любвеобилен. С 14 лет он начал посещать публичные дома. И, уже будучи женатым, продолжал наведываться к "веселым девкам", а также имел замужних любовниц.</p>

<h2>Гоголь В.Н. (19.03.1809 - 04.03.1852 гг.)</h2>
<p>Гpaммamuкa pуccкoгo языкa u pucoвaнuя эmo ocнoвныe пpeдмemы, в кomopыx xopoшo paзбupaлcя Huкoлaй.</p>
<p>Первой публикацией Гоголя стала поэма «Ганц Кюхельгартен», изданная им под псевдонимом «В. Алов», но критики восприняли её холодно. Разочарованный писатель выкупил вес оставшийся в продаже тираж и уничтожил его.</p>

<h2>Каверин В.А. (19.04.1902 - 2.05.1989 гг.)</h2>
<p>"Математика — самый короткий путь к самостоятельному мышлению." - цитата Каверина В.А.</p>

<h2>Никитин Д.В. (21.09.1824 - 16.10.1861 гг.)</h2>
<p>Учился будущий поэт в духовном училище и семинарии. Отец, в начале довольно состоятельный торговец, рассчитывал послать сына в университет, но дела его расстроились, и Иван Никитин вынужден был сделаться сидельцем при торговле восковыми свечами.</p>

<p>Грамоту маленький Иван Никитин освоил рано. Помог в этом ему сосед, который был сапожником, но весьма образованным. Научившись складывать буквы, Иван сразу начал сочинить свои первые стихи.</p>


{% endblock%}

mainapp/templates/mainapp/Top_interesting_authors.html
{% extends 'mainapp/base.html'%}

{% block title %}
    <title>Топ авторов</title>
{% endblock %}

{% block content %}
<div class="interesting_authors">
   <h1>Топ интересных авторов</h1>
    <h2>Топ авторов-классиков, по мненнию молодёжи на 2020 год</h2>
    <ul>
        {% for interesting_author in interesting_authors %}
            <li>
                {{interesting_author.title}}

            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mainapp/templates/mainapp/Top_interesting_books.html
{% extends 'mainapp/base.html'%}

{% block title %}
    <title>Топ книг</title>
{% endblock %}

{% block content %}
<div class="interesting_books">
    <h1>Топ интересных книг</h1>

    <h4>Топ – 5 бестеллеров 2020 год</h4>
    <ul>
        {% for interesting_book in interesting_books %}
            <li>
                {{interesting_book.title}}

            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {%block title%}
    <title>Читалочка</title>
    {%endblock%}
    {%block css%}
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/fontawesome-free-5.11.2-web/css/all.min.css">
    {%endblock%}
    {%block js%}
    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script src="/static/js/scripts.js"></script>
    {%endblock%}
</head>
<body>
{%block header%}
<nav>
  <ul class="topmenu">
    <li><a href="{%url 'index'%}">Читалочка</a></li>
      <li><a href="{%url 'Top_interesting_books'%}">Топ книг</a></li>
    <li><a href="{%url 'Bookstore'%}" class="down">Магазин</a>
      <ul class="submenu">
        <li><a href="{%url 'delivery'%}">Доставка/Оплата</a></li>
        <li><a href="{%url 'product'%}">Товар</a></li>
          <li><a href="{%url 'categories'%}">Категории</a></li>
        <li><a href="{%url 'Recently_published_books'%}">Вышедшие книги</a></li>
      </ul>
    </li>
    <li><a href="{%url 'The_authors'%}" class="down">Авторы</a>
      <ul class="submenu">
        <li><a href="{%url 'Top_interesting_authors'%}">Топ авторов</a></li>
        <li><a href="{%url 'Interesting_facts_in_the_world_of_books'%}">Факты</a></li>
      </ul>
    </li>
    <li><a href="{%url 'we'%}">О нас</a></li>

         {% if user.avatar %}
        <img src="{{ user.avatar.url }}" id="user_avatar">
        {% endif %}

    {% if user.is_authenticated %}
            <a href="{% url 'auth:edit' %}">
                {{user.first_name|default:"пользователь"}}
            </a>

            {% endif %}
            {% if user.is_authenticated %}
           <a href="{% url 'auth:logout' %}">Выход</a>
            {% else %}
            <a href="{% url 'auth:login' %}">Вход</a>
            <a href="{% url 'auth:register' %}">Регистрация</a>

    {% endif %}
  </ul>
</nav>
<!--<div id="up"><p class="pPageScroll">Вверх</p></div>-->
<!--<div id="down"><p class="pPageScroll">Вниз</p></div>-->
{%endblock%}
<div class="content">
{%block content%}
{%endblock%}
</div>

{%block footer%}
<footer>
    <p>&#169;KPK 2020</p>
</footer>
{%endblock%}
</body>
</html>

mainapp/templates/mainapp/categories.html
{% extends 'mainapp/base.html'%}

{% block title %}
    <title>Категории</title>
{% endblock %}
{% block content %}
<div class="book-categories">
	<h1>У нас есть следующие категории книг:</h1>
	<ul>
		{% for book_category in book_categories %}
			<li>
				<span id="category-{{bookCategories.pk}}">
					{{book_category.name}} </span>
					(возрасное ограничение {{book_category.min_age}} лет)
			</li>
    	{% endfor %}
		<div class="book_description col-lg-8"></div>
	</ul>
</div>

<div class="books">
	<h1>У нас есть следующие книги:</h1>
		<ul>
			{% for book in books%}
				 <li id="book-{{book.pk}}">
					 {{book.title}}</li>
					{{book.price}} руб. за книгу
			{%endfor%}
		</ul>
	<div class="book_categories_description col-lg-8"></div>
</div>

{% endblock %}
<div class="active-talk"></div>
<div class="send-message-form"></div>

mainapp/templates/mainapp/delivery.html
{% extends 'mainapp/base.html'%}

{% block content %}
<p>
    Доставка осуществляется двумя способами
    1 способ: Доставка служебными доставками.
    2 способ: Курьерская доставка
    От 1.500 р - доставка бесплатная
    Цена доставки зависит от удалённости региона
</p>
{% endblock %}

mainapp/templates/mainapp/error.html
{% extends 'base.html' %}

{% block content %}
<p>Ошибка на стороне сервера</p>
{% endblock %}

mainapp/templates/mainapp/fail.html
{% extends 'base.html' %}

{% block content %}
<p>Неудача</p>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html'%}

{% block title %}
    <title>Читалочка</title>
{% endblock %}
{% block content %}
    <h1>История первой книги</h1>
<h2>«Книги — корабли мысли, странствующие по волнам времени и бережно несущие свой драгоценный груз от поколения к поколению» — Фрэнсис Бэкон </h2>
<p>
<!--<h3>-->
   <!--История первой книги на Руси берет свое начало с эпохи правления царя Ивана Грозного.-->
      <!--А ведь именно при нем на Руси открывается первая типография — более чем 450 лет назад.-->
<!--А самыми очевидными причинами в учреждении первой типографии были, как и у всякого «здравомыслящего» государства — необходимость в развитии, расширение территорий, развитие в хозяйстве и торговле и т.д.-->
    <!--Доверие людей к переписчикам быстро иссякло, потому что никто не хотел читать дорогостоящие, не правдивые рукописи со скудным смыслом.-->
<!--В 1563 году первопечатниками на Руси стали Петр Мстиславец и Иван Федоров. Самым первым, точно датированным печатным изданием стала книга «Апостол», которая, в те времена, считалась основным учебником для изучения духовенства.-->
    <!--По ней учились монахи, крестьяне, дворяне. «Апостол» – это не просто книга, а своеобразная «Азбука» для церковно-приходских школ царских времен.-->
<!--Процесс выпуска книги «Апостол» оказался тяжелым и достаточно творческим, и занял у печатников целый год кропотливого труда.-->
<!--Первая печатная книга на Руси до сих пор является реликвией нашей Великой Державы.-->
    <!--Древнее издание «Апостол» – это родоначальник печатной промышленности, которая шаг за шагом вела общество к прогрессу, новым знаниям и самопознанию.-->
<!--</h3>-->
</p>

{% if peoples %}
<div class="exchange">
    <div class="exchange-members-list">
        {% for people in peoples %}
            <a class="exchange-member" href="{% url 'chat:show_talk' people.pk %}">
                {{people.last_name}} {{people.first_name}}
            </a>
        {% endfor %}
    </div>
    <div class="active-talk">
    </div>
    <div class="send-message-form">
    </div>
</div>
{% endif %}
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html'%}

{% block content %}
<div class="content">
    <div class="products"></div>
    <div class="cart">
        <div class="cart-title">
            <span class="text-bold cart-name">Корзина:</span>
            <span class="cart-score">0</span>
        </div>
        <div class="cart-products">

        </div>
        <div class="checkout">
            <form action="{{ form.target }}" method="POST">
                <p>{{ form.as_p }}</p>
                <p><input type="submit" value="Купить"></p>
            </form>
            <!--<form name="form" method="POST" action="">-->
            <!--{% csrf_token %}-->
            <!--<input class="checkout" type="submit" name="submit" value="Оформить заказ ₽"/>-->
            <!--</form>-->
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/we.html
{% extends 'mainapp/base.html'%}

{% block content %}
<p> Привет! Я - Читалочка. Тестируемый проект курсового и дипломного проекта. Создан я был в 2019 году весной
    во время курсового проектирования в ГБПОУ "КПК". Здесь много интересного - можно купить книгу, узнать Топ книг или авторов, поддчеркнуть для
    себя что-то новое и пообщаться в чате с другими участниками сайта.
    Автор: студентка 43 группы ГБПОУ "Курганский педагогический колледж" Анастасия А.Федулова
    Контакные данные: г.Курган
</p>

<div class="images">
    <a rel="static/img" class="photo" href="static/jmg/05.jpg" title="Картинка 1">
        <img src="static/jmg/05.jpg" width="150" height="100" alt=""/>
    </a>
</div>
{% endblock %}